<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-09-03T03:26:29 MYT" name="Default Suite" finished-at="2021-09-03T03:26:31 MYT" duration-ms="2785">
    <groups>
    </groups>
    <test started-at="2021-09-03T03:26:29 MYT" name="API_Response" finished-at="2021-09-03T03:26:31 MYT" duration-ms="2785">
      <class name="test.java.com.api.TestAPIResponse">
        <test-method signature="APITests(java.lang.String,java.lang.String,org.testng.ITestContext)[pri:0, instance:test.java.com.api.TestAPIResponse@1c72da34]" started-at="2021-09-03T03:26:29 MYT" name="APITests" data-provider="requestURL" finished-at="2021-09-03T03:26:31 MYT" duration-ms="2073" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://reqres.in/api/users/3]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://reqres.in/api/users/1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[org.testng.TestRunner@6ce139a4]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at test.java.com.api.TestAPIResponse.APITests(TestAPIResponse.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- APITests -->
        <test-method signature="APITests(java.lang.String,java.lang.String,org.testng.ITestContext)[pri:0, instance:test.java.com.api.TestAPIResponse@1c72da34]" started-at="2021-09-03T03:26:31 MYT" name="APITests" data-provider="requestURL" finished-at="2021-09-03T03:26:31 MYT" duration-ms="332" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://reqres.in/api/users/2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://reqres.in/api/users/2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[org.testng.TestRunner@6ce139a4]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- APITests -->
        <test-method signature="APITests(java.lang.String,java.lang.String,org.testng.ITestContext)[pri:0, instance:test.java.com.api.TestAPIResponse@1c72da34]" started-at="2021-09-03T03:26:31 MYT" name="APITests" data-provider="requestURL" finished-at="2021-09-03T03:26:31 MYT" duration-ms="181" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://reqres.in/api/users?page=2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://reqres.in/api/users?page=2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[org.testng.TestRunner@6ce139a4]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- APITests -->
        <test-method signature="APITests(java.lang.String,java.lang.String,org.testng.ITestContext)[pri:0, instance:test.java.com.api.TestAPIResponse@1c72da34]" started-at="2021-09-03T03:26:31 MYT" name="APITests" data-provider="requestURL" finished-at="2021-09-03T03:26:31 MYT" duration-ms="155" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://reqres.in/api/users?page=3]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://reqres.in/api/users?page=1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[org.testng.TestRunner@6ce139a4]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at test.java.com.api.TestAPIResponse.APITests(TestAPIResponse.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- APITests -->
      </class> <!-- test.java.com.api.TestAPIResponse -->
    </test> <!-- API_Response -->
  </suite> <!-- Default Suite -->
</testng-results>
